### ISSUE TITLE
ヾ(✿ﾟ▽ﾟ)ノ好耶！

### ISSUE THREAD

**Issue by Thomitics** [LXG-Shadow/Rhine-Department-0xf#1]
感谢，谢谢您能将新的代码分享出来供大家继续学习！ヾ(✿ﾟ▽ﾟ)ノ

**Comment by LXG-Shadow** [comment]
谢谢你的关注，

但是，本项目目前不会公开 - “由于特殊原因不会对外开放”

前一个项目Arknights-Dolos目前依旧可以使用
